// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edmxuhmphioyffxzxtpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkbXh1aG1waGlveWZmeHp4dHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MDI2MTIsImV4cCI6MjA1NDQ3ODYxMn0.yXSBmNvugK_WBZ2Rq-UnsSz9LUE4yKo4s8Gp70UhSOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);